/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laberinto01;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author sebastian
 */
public class Base extends javax.swing.JFrame {
    
    Dimension res_pantalla;
    int alto_pantalla = 0;
    int ancho_pantalla = 0;
    int alto_cuadros = 0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Base.class.getName());

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
        res_pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        
        Insets elementosVentana = getInsets();
        int barraTitulo = elementosVentana.top;
        
        alto_pantalla = res_pantalla.height;
        alto_cuadros = (alto_pantalla - barraTitulo)/9;
        
        while (res_pantalla.width < (alto_cuadros * 15)) {
            alto_cuadros--;
        }
        this.setSize( (alto_cuadros * 15), (alto_cuadros*9)+barraTitulo);
        
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 15; j++) {
                int posX = j*alto_cuadros;
                int posY = i*alto_cuadros;
                Cuadro c = new Cuadro(alto_cuadros, alto_cuadros, posX, posY);
                
//                if ( (i+j)%2 == 0 ) {
//                    c.cambiarColor(1);
//                }
                
                int color = Herramientas.alAzarEntre(1, 2);
                if (color == 2) {
                    color = Herramientas.alAzarEntre(2, 4);
                }
                
                c.cambiarColor(color);
                
                this.getContentPane().add(c);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Base().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
