/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laberinto01;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author sebastian
 */
public class Base extends javax.swing.JFrame {
    
    Dimension res_pantalla;
    int alto_pantalla = 0;
    int ancho_pantalla = 0;
    int alto_cuadros = 0;
    
    int cuadros_alto = 23;
    int cuadros_largo = 40;
    
    Cuadro[][] casilleros;  
    double[][] elevaciones;
    //ArrayList<Cuadro> casilleros = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Base.class.getName());

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
        
        casilleros = new Cuadro[cuadros_largo][cuadros_alto];
        elevaciones = new double[cuadros_largo][cuadros_alto];
        res_pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        
        Insets elementosVentana = getInsets();
        int barraTitulo = elementosVentana.top;
        
        alto_pantalla = res_pantalla.height;
        alto_cuadros = (alto_pantalla - barraTitulo)/cuadros_alto;
        
        while (res_pantalla.width < (alto_cuadros * cuadros_largo)) {
            alto_cuadros--;
        }
        this.setSize( (alto_cuadros * cuadros_largo), (alto_cuadros*cuadros_alto)+barraTitulo);
        
        //Reemplazamos el contenedor original del JFrame por uno con nuestros controles
        Mapa mapaBase = new Mapa(
                this.getContentPane().getWidth(), 
                this.getContentPane().getHeight(), 
                alto_cuadros
                );
        this.setContentPane(mapaBase);
        
        //crearMapa();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Base().setVisible(true));
    }

    public void crearMapa() {
    RuidoPerlin generador = new RuidoPerlin(System.currentTimeMillis());
    double escala = 0.1; // Cuanto más pequeño, más suaves las transiciones

    for (int x = 0; x < cuadros_largo; x++) {
        for (int y = 0; y < cuadros_alto; y++) {
            // Obtenemos un valor entre -1 y 1
            double valor = generador.noise(x * escala, y * escala);
            
            // Convertimos a 0.0 - 1.0 para que sea más fácil de manejar
            double elevacion = (valor + 1) / 2.0;

            // Aquí decides el terreno según la tabla que vimos antes
            if (elevacion < 0.15) casilleros[x][y].cambiarColor(Terreno.AGUA_PROFUNDA);
            else if (elevacion < 0.3) casilleros[x][y].cambiarColor(Terreno.AGUA);
            else if (elevacion < 0.5) casilleros[x][y].cambiarColor(Terreno.LLANURA);
            else if (elevacion < 0.7) casilleros[x][y].cambiarColor(Terreno.BOSQUE_LIGERO);
            else if (elevacion < 0.8) casilleros[x][y].cambiarColor(Terreno.BOSQUE_CERRADO);
            else if (elevacion < 0.9) casilleros[x][y].cambiarColor(Terreno.ROCAS);
            else casilleros[x][y].cambiarColor(Terreno.MONTANIA);
        }
    }
}
    
    
//    private void moverJugador(int direccion){
//        
//        int x = posicionJugadorX;
//        int y = posicionJugadorY;
//        
//        switch (direccion) {
//            case Terreno.DIRECCION_IZQUIERDA:
//                y++;
//                break;
//            case Terreno.DIRECCION_DERECHA:
//                y--;
//                
//                break;
//            default:
//                throw new AssertionError();
//        }
//        
//        
//        
//        casilleros[posicionJugadorX][posicionJugadorY].setOcupado(false);
//        casilleros[x][y].setOcupado(true);
//        
//        posicionJugadorX = x;
//        posicionJugadorY = y;
//        
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
