/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package laberinto01;

import java.awt.Color;

/**
 *
 * @author sebastian
 */
public class Cuadro extends javax.swing.JPanel {

    /**
     * Creates new form Cuadro
     */
    public Cuadro() {
        initComponents();
    }
    
    public Cuadro(int ancho, int alto, int x, int y) {
        initComponents();
        //this.setSize(ancho, alto);
        this.setBounds(x, y, ancho, alto);
        
    }
    
    public void cambiarColor(int color){
        switch (color) {
            case 1:
                this.setBackground(Color.white);
                break;
            case 2:
                this.setBackground(Color.black);
                break;
            case 3:
                this.setBackground(Color.orange);
                break;
            case 4:
                this.setBackground(Color.GREEN);
                break;
            default:
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
